markdown: rdiscount
permalink: /:title/
url: http://http://platina9.github.io
name: 范我闻
author: 范我闻
qq: 1420455572
email: vanplatina@gmail.com
weibo: 1725177444
github: Yonsm
pygments: true
safe: true
paginate: 20
about: "范我闻，九零后，建筑系学生。"
